import React from 'react';

import type { Metadata } from 'next';

import { geistMono, geistSans } from '@/assets/fonts';

import '@/assets/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

/**
 * RootLayout of the App.
 *
 * See this link to more information about layouts: https://nextjs.org/docs/app/getting-started/layouts-and-pages#creating-a-layout
 */
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
